### ISSUE TITLE
Full read SSRF in avatar upload

### ISSUE THREAD

**Issue by gregxsunday** [casdoor/casdoor#1187]
URLs for avatar upload are not restricted in any way. The attacker can set this to an arbitrary internal URL, eg. cloud metadata endpoint and the server will fetch it and store it on the server.

# Steps to reproduce
1. Set the avatar URL to an internal address, eg. `http://127.0.0.1/latest/meta-data/iam/security-credentials/baskinc-role`
![image](https://user-images.githubusercontent.com/26839305/194243115-7b367845-483a-409c-991a-a4a0f6ed8ae5.png)
This is the request that's sent under the hood:
![image](https://user-images.githubusercontent.com/26839305/194243253-2b23b389-3adf-4373-8db6-36ba78562cb4.png)
2. Go to `/files/images/avatar/built-in/admin.png` where `admin` is the username. This attack can be executed by a lower-privileged user as well.
![image](https://user-images.githubusercontent.com/26839305/194243370-0e1a16ca-771d-4f4d-8c5b-cfb3495f8348.png)

The response from the internal address will be stored there.

**Comment by hsluoyz** [comment]
This is not a bug

**Comment by hsluoyz** [comment]
@starbassma @gregxsunday if you have any further security-related reports, please follow intructions here: https://github.com/casdoor/casdoor/issues/1190 . This issue is valuable. We can continue the dicussion via Email. GitHub is not a good place to discuss those things because a lot of malicious attackers may utilize the information you have leaked to attack the systems.
