### ISSUE TITLE
Feature Request: Add API for Exam jwt Token

### ISSUE THREAD

**Issue by zzjin** [casdoor/casdoor#1303]
Add api to support check jwt token rights or not,
like sdk function `ParseJwtToken`, but can accept post request to casdoor api server to check if user's jwt token have persmmision or not, without known the application's `jwtPublicKey` 

Like:
https://docs.authing.cn/v2/guides/faqs/how-to-validate-user-token.html#%E5%9C%A8%E7%BA%BF%E9%AA%8C%E8%AF%81

**Comment by MagicalSheep** [comment]
Casdoor has implemented an API to support [RFC 7662: Token Introspection](https://oauth.net/2/token-introspection/). The API is located at `/api/login/oauth/introspect`. You can pass in `access_token` through this API to verify its validity. More information seeing [API documentation](https://door.casdoor.com/swagger/#/default/ApiController.IntrospectToken). 

As a reminder, `JWT Token` does not carry permission verification information, it is only used for user authentication rather than user authorization. If you want to get a tutorial on user authorization with Casdoor, please pay attention to the recently updated [Casdoor documentation](https://casdoor.org/docs/permission/overview). I'm working on this to provide more complete documentation of Casdoor permissions.

**Comment by hsluoyz** [comment]
@zzjin also see: https://casdoor.org/docs/how-to-connect/oauth#how-to-verify-accesstoken

Closed as resolved
