### ISSUE TITLE
[CAS] login view should prompt for the registration page

### ISSUE THREAD

**Issue by chenjpu** [casdoor/casdoor#1647]
![image](https://user-images.githubusercontent.com/1785778/224600542-283d2aab-9b4d-4fee-8ef0-9842927159ab.png)

**Comment by chenjpu** [comment]
mode=signup？
https://github.com/casdoor/casdoor/blob/2cca1c91364d38662d525552a7d2d31bf09f8801/web/src/EntryPage.js#L87

**Comment by hsluoyz** [comment]
@chenjpu have you enabled signup in application edit page? https://door.casdoor.com/applications/casbin/app-example

![image](https://user-images.githubusercontent.com/3787410/224601772-deedb3cf-b09a-4167-8a8b-db64c74838f9.png)

**Comment by chenjpu** [comment]
@hsluoyz yes, enabled

**Comment by hsluoyz** [comment]
@chenjpu the login text shown in the signup page has nothing to do with "/cas/:owner/:casApplicationName/login", can you clearly provide the steps to reproduce your issue? Also provide a demo video to show your issue

**Comment by hsluoyz** [comment]
Closed as stale

**Comment by hsluoyz** [comment]
This bug is reproduced: https://door.casdoor.com/cas/casbin/cas-java-app/login

![image](https://user-images.githubusercontent.com/3787410/232328299-05cde099-ed12-43d2-a95c-8ec3ad4da31a.png)

It should show "sign up" instead of "sign in" like this: https://door.casdoor.com/login

![image](https://user-images.githubusercontent.com/3787410/232328320-d2a1003a-3d30-44f1-aa89-cd88dd6e82e1.png)

And the href of this link is also wrong.

Related docs: https://casdoor.org/docs/how-to-connect/cas

Need to fix
