### ISSUE TITLE
Can ldap support custom filters?

### ISSUE THREAD

**Issue by ryanli870929** [casdoor/casdoor#1692]
Now ,we do't use the objectClass=posixAccount in the ldap server。so, i neet define the custom filters to search the users. 
so, will the casdoor support the custom filters in the future？

**Comment by hsluoyz** [comment]
@ryanli870929 hi, can you give more details? What LDAP server do you use? What kind of custom filters do you need?

And is this LDAP search API what you want? https://casdoor.org/docs/ldap/ldapserver#how-to-search

**Comment by lzw5399** [comment]
@hsluoyz 
Hi I have the same requirement, but now I had to connect to LDAP server directly in my business service instead of casdoor. Because currently casdoor only uses posixAccount to query users, which is a bit weak for actual scenarios(e.g. our customers may use `objectClass= inetOrgPerson`)
```go
SearchFilter := fmt.Sprintf("(&(objectClass=posixAccount)(uid=%s))", user.Name)
```

The specific implementation method can refer to jira(https://confluence.atlassian.com/adminjiraserver/connecting-to-an-ldap-directory-938847052.html). 
- the search filter is customizable
- user need to specify some mapping attr (such as mobile, phone), etc.
- the password hash method is also can be specified

**Comment by ryanli870929** [comment]
@hsluoyz , i use the objectClass= inetOrgPerson 。but the SearchFilter in the object/check.go and object/ldap.go are:
`SearchFilter := "(objectClass=posixAccount)"`。when i change the objectclass to “inetOrgPerson ” ，i can sync the users from ldap server to casdoor ，than  i can login by using the ldap users。
what i expect is that i can define the object class from the web。so i agress with lzw5399's suggestion.

**Comment by leo220yuyaodog** [comment]
@ryanli870929 The pr #1719 supports custom search filter. You can have a test.
@lzw5399 About mapping user field, my thought is we can add a select in web ldapEditPage. In the backend, build up the search filter string by the selected field. Then we can search the login user in ldap server according to the selected fields.

**Comment by hsluoyz** [comment]
@leo220yuyaodog sounds good. Go ahead!
