### ISSUE TITLE
Missing application name with Keycloak SAML login

### ISSUE THREAD

**Issue by fischermario** [casdoor/casdoor#1694]
The issue #1662 has not been resolved by PR #1676.

The PRs effect was that instead of a wrong application name "Casdoor" there is now no application name given in the payload to the POST call to the endpoint `/api/login`.

@hsluoyz
@leo220yuyaodog

As this is really not easy to demonstrate I have created a comprehensive example for you:

https://github.com/fischermario/casdoor-example/tree/saml-keycloak-6.0.1

Just clone this branch and follow the instructions. Please make sure that you run this on a real Linux system (no WSL on a Windows machine).

Thank you!

**Comment by leo220yuyaodog** [comment]
@fischermario I try to run the deploy.sh on centos 7.8 but failed.  But these answer may be helpful.

> there is now no application name given in the payload to the POST call to the endpoint` /api/login`

About pr #1676. For the saml provider, after idp redirect to `CASDOOR_ENDPOINT/callback`, casdoor frontend calls `/api/login` by use the clientId to idnetify the unique application, instead of the applicationName. So the payload do not has applicationName. You can use the `clientId` instead of applicationName in the payload to the POST call to the endpoint `/api/login`

**Comment by hsluoyz** [comment]
ping @fischermario

**Comment by fischermario** [comment]
@hsluoyz 

Sorry for the long silence. I understand that the empty application name property is now irrelevant. But why is the process now stuck?

@leo220yuyaodog 

Please try again with Ubuntu 22.04 LTS. I have not tested this with CentOS.

**Comment by hsluoyz** [comment]
@fischermario I don't think Ubuntu and CentOS have a lot of differences, since Casdoor is a high-level application compared to OS.

The question is, I am already lost and have forgot what this issue is. What bug is it? What you expect and what you got? Better with a GIF video to show the problem.

Does this issue have anything to do with Linux and Windows? Like I said `Casdoor is a high-level application compared to OS`?

Given this issue is also diverged with the application name, I suggest abandoning this issue. Propose a new one if you still hava bugs to report.
