### ISSUE TITLE
Keycloak SAML login stuck

### ISSUE THREAD

**Issue by fischermario** [casdoor/casdoor#1716]
The issues #1662 and #1694 were closed, but the problem that I'm observing was not resolved. I'm opening a new issue as I don't like commenting on closed issues.

As suggested by @hsluoyz I want to show you the broken flow in a short video:

![casdoor-saml-login](https://user-images.githubusercontent.com/10214295/230772124-49d097c5-d9f3-4f45-ac8e-fa37fc0872a6.gif)

**Hint:** The video **ends** with the Casdoor spinner turning and nothing happening anymore.

The following video shows the login using Casdoor directly (to illustrate that the application is working!):

![casdoor-local-login](https://user-images.githubusercontent.com/10214295/230772151-9104b5bc-9269-417a-9d9f-7a18b39a3e50.gif)

I tested this on CentOS 7.8 (as this is the preferred platform of @leo220yuyaodog). This shows the build process:

![casdoor-build](https://user-images.githubusercontent.com/10214295/230772197-82c1cf1b-9138-4087-9c3a-8e1c6c940531.gif)

@leo220yuyaodog Please tell me what part of the deploy script didn't work for you.

Again the example can be cloned from this repository:

[https://github.com/fischermario/casdoor-example/tree/saml-keycloak-6.0.1](https://github.com/fischermario/casdoor-example/tree/saml-keycloak-6.0.1)

Please make sure that you have Docker installed according to this manual:

[https://docs.docker.com/engine/install/centos/](https://docs.docker.com/engine/install/centos/)

Thank you!

**Comment by hsluoyz** [comment]
@fischermario can you try directly login via KeyCloak from Casdoor's org login page (so your app is not involved and no 2nd jump)?

Like: https://door.casdoor.com/login/casbin

![image](https://user-images.githubusercontent.com/3787410/230772884-d0f28d1d-0842-4eb2-89d2-8fc2c36b606c.png)

**Comment by fischermario** [comment]
@hsluoyz

I just tried what you suggested (use Keycloak to log in to app-built-in). Unfortunately the result is the same. Do you want me to make a video of the process?

**Comment by hsluoyz** [comment]
@fischermario yes, a video will be good

**Comment by leo220yuyaodog** [comment]
@fischermario 
1. Because of nslookup failed, so I comment the dns check.
![image](https://user-images.githubusercontent.com/71440988/232113264-db341a8d-1dfb-49f4-8623-c91c74d7d1ed.png)
2. Then I meet the problem, can you help me?
![image](https://user-images.githubusercontent.com/71440988/232113240-4750718d-b246-4a55-9012-ad07263bdcf8.png)

About the crash screen, it seems that Casdoor failed to parse the samlResponse from keycloak. Does your script initialize `origin` in app.conf.  It is required for using saml sp.

https://github.com/fischermario/casdoor-example/blob/85331fa3d9fa9f6734247c8706fa68cab99723e4/conf/casdoor.conf-template#L18

**Comment by leo220yuyaodog** [comment]
@fischermario Oh, I reproduce your problem. Maybe the problem will be resolved. It caused by the wrong config. As below picture shows: the issue url need be same as the idp attribute entityID:

![image](https://user-images.githubusercontent.com/71440988/232226931-316d5bd0-4044-463f-a98b-2889c711b2a6.png)

or will report error when login:

![image](https://user-images.githubusercontent.com/71440988/232226984-def21536-c8c9-4ca8-b2ef-befcf61f6133.png)
