### ISSUE TITLE
[BUG] permisson enforce, parse params error with interface{}

### ISSUE THREAD

**Issue by shiningstarts** [casdoor/casdoor#1843]
```json
{
    "status": "error",
    "msg": "json: cannot unmarshal object into Go value of type []interface {}",
    "sub": "",
    "name": "",
    "data": null,
    "data2": null
}
```
https://github.com/casdoor/casdoor/blob/73b9d73f6492539d2bc73121b039c887e428378b/object/permission_enforcer.go#LL223C23-L223C23

**Comment by hsluoyz** [comment]
@shiningstarts what's your request body? Is it an array in JSON?

**Comment by thanhtinhpas1** [comment]
@shiningstarts We have a breaking change for `/api/enforce` API in this [commit](https://github.com/casdoor/casdoor/commit/776a682fae5a9f8f749f2dcf2080cd470c585ae0) I think so.

**Comment by iPortNe** [comment]
It seems that the args of enforce change from {"id":"example-org/example-permission", "v0":"example-org/example-user", "v1":"example-resource", "v2":"example-action"} to ["example-org/example-user","example-resource","example-action"].
Additional parameters permissionId and modelId are relocated in url params.

Btw, current return of enforce is confusing. It returns an array of boolean which seems to be the result of merely the enforcement test of every policy in a model. The client can not distinguish from an array of boolean whether an action should be permitted.
The meanful result should be a boolean value rather than a bunch of it.

**Comment by shiningstarts** [comment]
> It seems that the args of enforce change from {"id":"example-org/example-permission", "v0":"example-org/example-user", "v1":"example-resource", "v2":"example-action"} to ["example-org/example-user","example-resource","example-action"]. Additional parameters permissionId and modelId are relocated in url params.
> 
> Btw, current return of enforce is confusing. It returns an array of boolean which seems to be the result of merely the enforcement test of every policy in the model. The client can not use an array of boolean to determin whether an action should be permitted. The meanful result should be a boolean value rather than a bunch of it.

It seems that, it runs ok with exposed casbin apis(https://casdoor.org/docs/permission/exposed-casbin-apis) before v1.3.
I wonder why is enforce-api not backward compatible, upgrading SDK for all access parties requires a lot of work, and is not smooth.

**Comment by shiningstarts** [comment]
> @shiningstarts We have a breaking change for `/api/enforce` API in this [commit](https://github.com/casdoor/casdoor/commit/776a682fae5a9f8f749f2dcf2080cd470c585ae0) I think so.

It seems that.

**Comment by hsluoyz** [comment]
@shiningstarts sorry for making this inconvenience. You can stay on using a Casdoor version before this commit: https://github.com/casdoor/casdoor/commit/776a682fae5a9f8f749f2dcf2080cd470c585ae0

Closed here
