### ISSUE TITLE
 Not expected URIs in openId configuration

### ISSUE THREAD

**Issue by yamaritta** [casdoor/casdoor#2037]
Hi!

In our case, there are two docker containers in a closed network.
One of them is casdoor and other service works with casdoor via http.
When we make http-request to get configuration, server returns https URIs
![image](https://github.com/casdoor/casdoor/assets/41572091/a1eff84d-4fe6-46b3-b0f4-476f0f8419a3)

At the same time localhost returns correct URIs on the same request, but localhost can't be used for connection between containers.
![image](https://github.com/casdoor/casdoor/assets/41572091/2faddbe7-6c1e-4626-ae51-961a8343f9e2)

Сould you please return addresses with the protocol of the original request?

**Comment by hsluoyz** [comment]
@yamaritta fixed in: https://github.com/casdoor/casdoor/commit/855259c6e7467b29ca502107eeca3b3f420b492c

Even without the fix, you can specify the `origin` param in app.conf to get the issue resolved

https://github.com/casdoor/casdoor/blob/28297e06f736a14918ce59a9ae11b59b52331cf0/object/oidc_discovery.go#L62-L80
