### ISSUE TITLE
Feature Request: Support for Custom Login Page Using Vue.js

### ISSUE THREAD

**Issue by promptonce** [casdoor/casdoor#2273]
Is your feature request related to a problem? Please describe.
Casdoor currently allows customization of the login page through HTML and CSS. However, it does not support more modern frontend frameworks like Vue.js for this purpose.

Describe the solution you'd like
It would be great if Casdoor could extend its customization capabilities to include Vue.js. This would provide developers greater flexibility and better ways to integrate the login functionality into existing Vue.js applications.

Describe alternatives you've considered
An alternative could be manually translating Vue.js components into HTML and CSS for integration but this would not be a straightforward or easily maintainable solution.

Additional context
Vue.js is widely adopted and having built-in support for Vue.js-based customization in Casdoor could attract more developers to use it.

**Comment by luyentm** [comment]
I love this Feature Request.

**Comment by mdxiaohu** [comment]
Are there any progress now .

**Comment by promptonce** [comment]
no



At 2023-11-23 11:18:50, "mdxiaohu" ***@***.***> wrote:

Are there any progress now .

**Comment by hsluoyz** [comment]
This issue is really not good-positioned because you try to eliminate the existence of Casdoor by trying to use a whole bulk of new frontend. This is against our intial goal to advocate it as a free and open-source project.

My point is that we will definitely not put this on the high priority list for oursevles. But if someone has provided a very mature solution about it, we are happy to accept its existence.
