### ISSUE TITLE
Email or phone cannot be reset from the client via the public API

### ISSUE THREAD

**Issue by jianmaikj** [casdoor/casdoor#2379]
it will return `The user: app/app_name doesn't exist`

**Comment by hsluoyz** [comment]
@jianmaikj what API did you call? Can you provide the call stack for the error?

**Comment by jianmaikj** [comment]
> @jianmaikj what RESTful API did you call? Can you provide the call stack for the error?

`/api/reset-email-or-phone`

**Comment by hsluoyz** [comment]
@jianmaikj fixed by: https://github.com/casdoor/casdoor/commit/150e3e30d5103a88bd3ad8d026d4538709f18893

This API `/api/reset-email-or-phone` requires user impersonation (aka you need to act as a user to reset email/phone for himself), you can use impersonation to authenticate the API like: http://localhost:8000/api/reset-email-or-phone?clientId=294b09fbc17f95daf2fe&clientSecret=dd8982f7046ccba1bbd7851d5c1ece4e52bf039d&userId=built-in/admin

It will authenticate with clientId/clientSecret and but act as the userId
