### ISSUE TITLE
How to manage access to application

### ISSUE THREAD

**Issue by fischermario** [casdoor/casdoor#2410]
I need help to implement the following scenario:

The organzation *org-test* contains one application *app-test*. Users can register new accounts. There is also an AzureAD provider that automatically creates a new user whenever someone logs into the application using this provider (if this user did not already exist). Users who can use the AzureAD provider are employees of the organization (everybody has the same company domain *test.com* in their email address). Users who just registered an account using email/password are customers.

Customers who log into the application using email/password should not have access to the application *app-test* unless they get permission to do so (e.g. an administrator adds a specific user to a group). Employees who log into the application using the AzureAD provider should have immediate access to the application (without any manual intervention).

How can this be achieved?

**Comment by fischermario** [comment]
@hsluoyz Can you give me a hint? Or is this maybe out of scope for Casdoor?

**Comment by hsluoyz** [comment]
@fischermario fixed by: https://github.com/casdoor/casdoor/commit/98defe617b13b80a725c3719bb2b4f9bc2c6b44d

Add your group name to the `Signup group` column of the OAuth provider row in the "Providers" table of application edit page:

![image](https://github.com/casdoor/casdoor/assets/3787410/7a3de1a9-1ed8-4a28-8ce8-f680243ba2e1)
