### ISSUE TITLE
Docker image for arm64?

### ISSUE THREAD

**Issue by jum** [casdoor/casdoor#2416]
I am trying the casdoor docker image on the docker hub and it does not appear to support arm64:

```
! casdoor The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Is there anything that can be done by that?

**Comment by hsluoyz** [comment]
@jum arm64 build was removed from CI because it's too slow: https://github.com/casdoor/casdoor/pull/2390

The last version that supports arm64 DockerHub build is v1.428.0, you can use this version: https://hub.docker.com/layers/casbin/casdoor/v1.428.0/images/sha256-dca69125720cbf1607dcd2d8e311fbc1b658577d9e85b3475fd5590f9f7b460f?context=repo

https://hub.docker.com/repository/docker/casbin/casdoor/tags?page=1&ordering=last_updated

![image](https://github.com/casdoor/casdoor/assets/3787410/c8b4738b-998d-4869-bece-2be02dc63053)

**Comment by jum** [comment]
Managed to build my own multi-arch container. My observation is that the frontend build is the longest part, so if this would be build only once instead of for each arch it would probably by much faster.

**Comment by emeryao** [comment]
the slow building may related to the cnpm proxy of https://registry.npmmirror.com at https://github.com/casdoor/casdoor/commit/9aec69ef4744f5f49ef8a6605a44a17eada8c65d#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L4

removing the proxy may speed up the building process

Can we please give it another try ?

really need the arm64 docker image

Thanks in advance 😄

**Comment by emeryao** [comment]
@hsluoyz

**Comment by hsluoyz** [comment]
@emeryao not planned to add it back, you can build the image by yourself

**Comment by hsluoyz** [comment]
Thanks to this PR: https://github.com/casdoor/casdoor/pull/2969 , the arm64 image is back starting from v1.621.0: https://hub.docker.com/r/casbin/casdoor/tags
