### ISSUE TITLE
GitHub Login Does Not Retrieve User Email in Casdoor

### ISSUE THREAD

**Issue by Cloud-Scrapehero** [casdoor/casdoor#3100]
When signing in with GitHub, the prompt asks to allow access to the user's email. However, after signing in, the user's email is not displayed on the Casdoor users page. In contrast, signing in with Google successfully retrieves and displays the user's email.

### Steps to Reproduce:

Sign in using GitHub.
Allow access to the email.
Check the Casdoor users page.

### Expected Behavior:

The user's email should be displayed on the Casdoor users page after signing in with GitHub.

### Actual Behavior:

The user's email is not available on the Casdoor users page after signing in with GitHub.

### Additional Information:

Google login works as expected and displays the user's email.

**Comment by hsluoyz** [comment]
@Cloud-Scrapehero can you make a PR to fix it?

**Comment by EZ4Jam1n** [comment]
Hello, @Cloud-Scrapehero

Regarding the issue where the user's email is not displayed after signing in with GitHub, this occurs because the GitHub OAuth API returns `null` for the email if it is set to private. As a result, the email cannot be displayed on the Casdoor users page.

If you want your email to be displayed in the Casdoor user interface, you need to make your email address public in your GitHub settings and choose one as your primary email for display. 

To make your email public, go to the email settings in GitHub, and uncheck the option as shown below:
![image](https://github.com/user-attachments/assets/65982f14-26e5-4cad-b306-7aaab9b0522f)


If you have any other suggestions or solutions, feel free to discuss them further.

**Comment by hsluoyz** [comment]
Closed as resolved
