### ISSUE TITLE
Casdoor's token logs are not deleted after expiration

### ISSUE THREAD

**Issue by rainpaper-bs** [casdoor/casdoor#3123]
Casdoor's token logs are not deleted after expiration, which causes the data to grow over the years, and the logs from a long time ago still exist. This function is in the token option under Logging & Auditing, and I can see the tokens that have expired a long time ago. In order to improve the efficiency of the system operation and save space, the logging of these expired tokens should be deleted.

**Comment by hsluoyz** [comment]
@rainpaper-bs can you make a PR?

**Comment by hsluoyz** [comment]
Low priority work, let your DBA do the job

**Comment by slow-groovin** [comment]
It would be ideal to have an automatic deletion option, or at least documentation explaining how to make choice to delete it manually or preserve it . As a user not proficient with the auth system and is using Casdoor for that reason, if I don’t notice the token page, it will lead to data accumulation in production. Even if I do notice, I’m still unsure about whether I should delete it or not.

**Comment by hsluoyz** [comment]
@slow-groovin like I already said, we are open to PRs but we ourselves will not put efforts into it. Because it makes your company's DBA take salary happily without doing any job. Why let OSS guys do your DBA's job? The OSS community's focus is not on that part yet, lots of more important things to do than making DBA just happily drink coffee

**Comment by slow-groovin** [comment]
Thanks for your reply. I know that. It's just a suggestion for low-priority thing. I do DEV&OP&DBA all, so from my perspective, I hope less manually operations.
