### ISSUE TITLE
Bug: Incomplete Logout Process in SSO Single Sign-On (SSO) System

### ISSUE THREAD

**Issue by Blackcbears** [casdoor/casdoor#3159]
We have identified a bug in the Single Sign-On (SSO) system related to the logout process. When a user logs out by sending a request to /api/logout, the system does not always complete the logout correctly, leading to potential security risks.

Steps to Reproduce:

1.Open SSO for casbin/app-saas located in demo casdoor
2.Send a login request to https://demo.casdoor.com/cas/casbin/app-saas/login?service=http://localhost:9000/callback login system.
3.Send a login request to https://demo.casdoor.com/cas/casbin/app-saas/logout?service=http://localhost:9000/callback logout system, `/api/logout` return ok
4.Open Home Page， https://demo.casdoor.com, Description Failed to log out

I tried the test and found logout, but the session in redis was not cleared.

Maybe instead of doing c.ClearUserSession() in `/api/logout`, you do execution c.DestroySession()

**Comment by ZhaoYP-2001** [comment]
> We have identified a bug in the Single Sign-On (SSO) system related to the logout process. When a user logs out by sending a request to /api/logout, the system does not always complete the logout correctly, leading to potential security risks.
> 
> Steps to Reproduce:
> 
> 1.Open SSO for casbin/app-saas located in demo casdoor 2.Send a login request to https://demo.casdoor.com/cas/casbin/app-saas/login?service=http://localhost:9000/callback login system. 3.Send a login request to https://demo.casdoor.com/cas/casbin/app-saas/logout?service=http://localhost:9000/callback logout system, `/api/logout` return ok 4.Open Home Page， https://demo.casdoor.com, Description Failed to log out
> 
> I tried the test and found logout, but the session in redis was not cleared.
> 
> Maybe instead of doing c.ClearUserSession() in `/api/logout`, you do execution c.DestroySession()

I found that this problem is due to the problem of session updates being overwritten when beego has concurrent requests (https://github.com/beego/beego/issues/2666). Our c.ClearUserSession() updates the username in the session to a null value, but it is overwritten by other concurrent requests when the front end is loaded. In other words, although logout returns ok, it is not actually successfully logged out.

I plan to add a callback function to logout, which will query whether the logout has been successful. If not, I will call logout again. Since concurrency only occurs during the initial access and subsequent logouts are not affected by concurrency, I think this can solve your problem.

Do you have any better suggestions?

**Comment by ZhaoYP-2001** [comment]
> We have identified a bug in the Single Sign-On (SSO) system related to the logout process. When a user logs out by sending a request to /api/logout, the system does not always complete the logout correctly, leading to potential security risks.
> 
> Steps to Reproduce:
> 
> 1.Open SSO for casbin/app-saas located in demo casdoor 2.Send a login request to https://demo.casdoor.com/cas/casbin/app-saas/login?service=http://localhost:9000/callback login system. 3.Send a login request to https://demo.casdoor.com/cas/casbin/app-saas/logout?service=http://localhost:9000/callback logout system, `/api/logout` return ok 4.Open Home Page， https://demo.casdoor.com, Description Failed to log out
> 
> I tried the test and found logout, but the session in redis was not cleared.
> 
> Maybe instead of doing c.ClearUserSession() in `/api/logout`, you do execution c.DestroySession()

I found that this problem is due to the problem of session updates being overwritten when beego has concurrent requests (https://github.com/beego/beego/issues/2666). Our c.ClearUserSession() updates the username in the session to a null value, but it is overwritten by other concurrent requests when the front end is loaded. In other words, although logout returns ok, it is not actually successfully logged out.

I plan to add a callback function to logout, which will query whether the logout has been successful. If not, I will call logout again. Since concurrency only occurs during the initial access and subsequent logouts are not affected by concurrency, I think this can solve your problem.

Do you have any better suggestions?
