### ISSUE TITLE
Slow review time.

### ISSUE THREAD

**Issue by rafaelgfirmino** [casdoor/casdoor#469]
I noticed that some pull requests get stuck for a long time.

Casdoor seems to me to have immense potential, but it is frustrating for contributors not to have any kind of feedback or simply for reviewers not to approve.
I also noticed that the reviewers @seriouszyx and tangyang9464 take a long time or almost never review commits and @hsluoyz always merges without revisions.

I would like to know if you guys are thinking about how to improve this point, does it make sense to have so many people to review?

**Comment by hsluoyz** [comment]
Hi @rafaelgfirmino , thanks for being interested in Casdoor!

> I noticed that some pull requests get stuck for a long time.

Most PRs are kept for archive purpose, next we will take some time to analyze (and maybe close) them one by one. There're no valuable PRs waiting to be merged in that list.

> I also noticed that the reviewers @seriouszyx and tangyang9464 take a long time or almost never review commits

The automatically set reviewers: @seriouszyx and @tangyang9464 will be no active in near future. This is done by our casbin-bot: https://github.com/casbin/casbin-oa . I didn't update the new reviewers in the bot config. The right persons have been updated: https://oa.casbin.com/issues/issue_all_casdoor

> and @hsluoyz always merges without revisions.

I do code review, you didn't see my review comments in most occasions because we use other channels like instant messaging to directly talk about PR problems as it's faster than texting:) But of course if there's no such connection with the PR author, like a first-time contributor, we will also use GitHub.

**Comment by rafaelgfirmino** [comment]
Thanks for the answer.
