### ISSUE TITLE
Incomplete support for samesite attribute

### ISSUE THREAD

**Issue by zhuqiangqiang** [casdoor/casdoor#714]
`beego.BConfig.WebConfig.Session.SessionCookieSameSite = http.SameSiteNoneMode`

When samesite is set to none, you need to use the secure property in the latest browser version. The current beego version does not support direct configuration of secure properties

**Comment by hsluoyz** [comment]
@halozhy plz follow up with this issue

**Comment by halozhy** [comment]
I tried using the latest 2.0.2 version of beego to write a test program, and set `beego.BConfig.WebConfig.Session.SessionCookieSameSite = http.SameSiteNoneMode`, but the `Secure` flag is still not added to the Set-Cookie request header

After that, I checked the source code of beego version 2.0.2 at [server/web/session/session.go#L218](https://github.com/beego/beego/blob/v2.0.2/server/web/session/session.go#L218). I found that the `Secure` flag was determined by the [`isSecure`](https://github.com/beego/beego/blob/v2.0.2/server/web/session/session.go#L359) function, check this function and you can find that only in the case of HTTPS, beego will add the `Secure` flag to the session

The beego v1.12.3 currently used by Casdoor also handles the `Secure` flag in this way. In beego v1.12.3's source code: [session/session.go#L311](https://github.com/beego/beego/blob/v1.12.3/session/session.go#L311), the `isSecure` function is also called to determine whether it is necessary add the `Secure` flag

In order to verify this, I used the mkcert tool to generate a certificate `localhost.pem` and the corresponding key `localhost-key.pem`. Then I put them all in the `conf` folder, and added the following configuration to the `conf/app.conf` file 


````
EnableHTTPS=true
EnableHttpTLS=true
HttpsPort=8010
HTTPSCertFile = "conf/localhost.pem"
HTTPSKeyFile = "conf/localhost-key.pem"
````

After that, I start Casdoor, clear the existing cookies and visit https://localhost:8010/, it can be seen that the session has been successfully set, and the `Secure` flag exists at this time

![img_session has been successfully set](https://user-images.githubusercontent.com/56069009/166435704-18635b42-3e50-4c7b-9bb6-123f228a7a57.png)

Therefore, I think this problem can not be solved by upgrading the beego's version. If you really need to set `SameSite=None` for the session, you should use the HTTPS protocol at the same time, which is also consistent with the MDN document.

> [`SameSite=None` requires `Secure`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#samesitenone_requires_secure)
>
> A [`Secure`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#secure) cookie is only sent to the server with an encrypted request over the HTTPS protocol. Note that insecure sites (`http:`) can't set cookies with the `[Secure](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#secure)` directive.

**Comment by hsluoyz** [comment]
Closed as resolved.
