### ISSUE TITLE
[question] why not using https://github.com/beego/beego ?

### ISSUE THREAD

**Issue by muharihar** [casdoor/casdoor#919]
Dear Team,

Just want to know, why casdoor not using https://github.com/beego/beego instead of https://github.com/astaxie/beego ?

Thank you!

**Comment by hsluoyz** [comment]
@muharihar the Beego team changed their repo from https://github.com/astaxie/beego to https://github.com/beego/beego after we used it. And the v1 version we used (we prefer to use v1 version because it's enough stable) is still using https://github.com/astaxie/beego as import paths. So we cannot switch to beego/beego even if we want to do it.

**Comment by gitlawr** [comment]
V1 is maintained under https://github.com/beego/beego now: https://github.com/beego/beego/blob/v1.12.11/go.mod#L1
Can we switch to it at the moment?
It helps to resolve known CVEs: https://github.com/advisories/GHSA-qx32-f6g6-fcfr

**Comment by hsluoyz** [comment]
@gitlawr fixed in: https://github.com/casdoor/casdoor/commit/04709f731bb553e8b4a03fc12ad2330f6e22cb62
