### ISSUE TITLE
Database exception occurred when using wechatMiniProg to request login

### ISSUE THREAD

**Issue by Linvery** [casdoor/casdoor#998]
![image](https://user-images.githubusercontent.com/23356865/183743447-8d9bfa93-2aac-4f2b-927c-fa279f9e5405.png)
![image](https://user-images.githubusercontent.com/23356865/183743954-a4e6e639-a591-4525-8bc4-797f3a55ab87.png)
![image](https://user-images.githubusercontent.com/23356865/183744019-eba2f919-fd00-44a3-b22d-88b6db10b702.png)
When I try to use the wechat MiniProg to request the login of casdoor according to the official document, I return the error casdoor: error 1054: unknown column 'unionid' in 'where claim'

**Comment by hsluoyz** [comment]
@dirname

**Comment by dirname** [comment]
Could you provide your casdoor version?

**Comment by Linvery** [comment]
> Could you provide your casdoor version?

yes,I Could.
casdoor-1.84.0.zip downloaded from GitHub releases
In addition, this is a wechat miniProg about https://api.weixin.qq.com/sns/jscode2session Screenshot of the request
![image](https://user-images.githubusercontent.com/23356865/183821429-5da16091-22ab-4d17-a3b9-860a57775b07.png)
The return value contains unionid.
If you have any additional information, please ask me

**Comment by dirname** [comment]
> > Could you provide your casdoor version?
> 
> yes,I Could. casdoor-1.84.0.zip downloaded from GitHub releases In addition, this is a wechat miniProg about https://api.weixin.qq.com/sns/jscode2session Screenshot of the request ![image](https://user-images.githubusercontent.com/23356865/183821429-5da16091-22ab-4d17-a3b9-860a57775b07.png) The return value contains unionid. If you have any additional information, please ask me

https://github.com/casdoor/casdoor/blob/b14554a5ba18434f6f479bd77b1ec024362e43d9/object/user.go#L245-L249

This bug is because unionid does not declare the field name in xorm, so the field name in the database is default as `we_chat_union_id`

https://github.com/casdoor/casdoor/blob/b14554a5ba18434f6f479bd77b1ec024362e43d9/object/user.go#L78-L81

The `WeChatUnionId` is deprecated now, see #985 .

Plz, upgrade ur casdoor version after v1.84.1.
